---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.12
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: frontend-prettier
        name: Prettier (Frontend)
        # We use "." so it formats everything in /frontend 
        # that isn't ignored by .prettierignore
        entry: pnpm --dir frontend exec prettier --write .
        language: system
        files: ^frontend/
        pass_filenames: false # This is the magic key

      - id: frontend-eslint
        name: ESLint (Frontend)
        entry: bash -c 'cd frontend && pnpm exec eslint --fix' 
        # --config eslint.config.mjs --ignore-path .eslintignore'
        language: system
        files: ^frontend/.*\.(js|ts|vue|mjs)$
        pass_filenames: false

