services:
  franking-dev:
    container_name: franking-dev
    image: franking:dev
    env_file:
      - .env
    ports:
      - 8567:8000
    volumes:
      - /opt/docker/invio/labels:/app/labels
      - /opt/docker/invio/data/invio.db:/app/invio.db:ro
      - /var/run/cups/cups.sock:/var/run/cups/cups.sock
      - /etc/cups:/etc/cups:ro
